# Generated by Django 5.2.17 on 2026-09-05 20:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('company', models.CharField(blank=True, max_length=120, verbose_name='empresa')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('due_date', models.DateField(verbose_name='fecha de entrega')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Finalizado')], default='pending', max_length=20, verbose_name='estado')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='medium', max_length=10, verbose_name='prioridad')),
                ('manual_progress', models.PositiveSmallIntegerField(blank=True, help_text='Valor entre 0 y 100. Vacío para calcularlo automáticamente.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='progreso manual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.client', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'proyecto',
                'verbose_name_plural': 'proyectos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(verbose_name='descripción')),
                ('due_date', models.DateField(verbose_name='fecha límite')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='entregado')),
                ('delivered_at', models.DateField(blank=True, null=True, verbose_name='fecha de entrega real')),
                ('simulated_file', models.CharField(blank=True, help_text='Nombre o ruta simulada del archivo.', max_length=255, verbose_name='archivo simulado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'entregable',
                'verbose_name_plural': 'entregables',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ClientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Cliente', max_length=120, verbose_name='autor')),
                ('content', models.TextField(verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'comentario del cliente',
                'verbose_name_plural': 'comentarios del cliente',
                'ordering': ['-created_at'],
            },
        ),
    ]
